### ISSUE TITLE
I want the site icons to be displayed when all the news is selected.

### ISSUE THREAD

**Issue by rubel-22** [SmartRSS/Smart-RSS#107]
The latest version of smart_rss_reader-2.13.0-fx works fine!
Thank you for the great extension for Firefox Quantum.
I didn’t go over to Firefox Quantum for a long time because there was no extension for reading RSS
like NewsFox. Now smart_rss_reader has completely replaced NewsFox.
Well, I really want site icons to appear when all the news is selected.
It would be very visual and convenient.
But this is only at your request.
https://i111.fastpic.ru/big/2020/0323/f3/477c5a15ca77951f7aa14bcddadd0bf3.png
https://i111.fastpic.ru/big/2020/0323/7d/1fad2da6249f5142736d0b4a2390477d.png

**Comment by zakius** [comment]
relates #66

**Comment by rubel-22** [comment]
Or you can make the icon appear in front of the title bar, and not below the line, as in NewsFox.
It will be more convenient visually. In general, the smart_rss_reader-2.19.0-fx version works fine, thanks.

**Comment by zakius** [comment]
I've been fiddling with positioning quite long and this is the best solution I managed to come up with, if you are able to provide markup and styles that work better I'll gladly accept them but I don't want to spend too much time on UI unless something is clearly broken as I'm just not comfortable with it

**Comment by rubel-22** [comment]
Ок. Спасибо за внимание. К сожалению, я простой пользователь и в CSS совершенно
ничего не понимаю. Правда, я отредактировал ваш файл main.css и убрал не нужные мне иконки в интерфейсе, сменил фон. Получилось вот так:
[url=https://i114.fastpic.ru/big/2021/0102/e9/_4c49cddd36d3d8e4bbc1aedc4700cfe9.png][img]https://i114.fastpic.ru/big/2021/0102/77/6ff4c73063f0718d1e430069c46e2777.png[/img][/url]
