### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [SmartRSS/Smart-RSS#109]
![image](https://user-images.githubusercontent.com/192271/79065990-490c8d80-7cac-11ea-9448-8643bc9edbcb.png)

https://addons.mozilla.org/addon/smart-rss-reader/versions/2.15.1/updateinfo/ empty, can you make release notes visible at AMO for future releases? 

Thanks. 

In the meantime I see https://github.com/zakius/Smart-RSS/releases but there's no 2.15.1

**Comment by zakius** [comment]
this release went pretty sloppy, had to pull back 2.15.0 because package was malformed and forgot to paste notes when pushing the patched one, I'll add them when I find some time

sorry for the inconvenience

**Comment by grahamperrin** [comment]
:-) OK, no problem
