### ISSUE TITLE
[bug] stopped working on Apr 11

### ISSUE THREAD

**Issue by ingvar-lynn** [SmartRSS/Smart-RSS#111]
I am getting mostly empty page save for three buttons in top left corner and two vertical bars.
An error from console:

```
TypeError: view is undefined Layout.js:39:17
    attach moz-extension://3ae44f9b-9882-454f-9d09-c7e5bebb2e24/scripts/app/layouts/Layout.js:39
    initialize moz-extension://3ae44f9b-9882-454f-9d09-c7e5bebb2e24/scripts/app/layouts/FeedsLayout.js:36
    Backbone 4
    attach moz-extension://3ae44f9b-9882-454f-9d09-c7e5bebb2e24/scripts/app/layouts/Layout.js:48
    start moz-extension://3ae44f9b-9882-454f-9d09-c7e5bebb2e24/scripts/app/app.js:83
    <anonymous> moz-extension://3ae44f9b-9882-454f-9d09-c7e5bebb2e24/scripts/main.js:34
    execCb moz-extension://3ae44f9b-9882-454f-9d09-c7e5bebb2e24/scripts/libs/require.js:5
    check moz-extension://3ae44f9b-9882-454f-9d09-c7e5bebb2e24/scripts/libs/require.js:5
 ...
```

I cannot reproduce this bug on empty profile.

**Comment by zakius** [comment]
package for 2.15.0 was malformed, I pulled it back as soon as I realized that and soon later uploaded patched one

you must've been unlucky to get updates checked during that window when 2.15.0 was available, next automated check will happen in few days, but you can force it yourself in extensions manager, that should cause 2.15.1 to be installed

sorry for the inconvenience

I'm not closing this issue to make it easier to discover if someone else encounters this problem

**Comment by ingvar-lynn** [comment]
Update solved the problem indeed.
Thanks.
