### ISSUE TITLE
Print functionality prints everything except contents

### ISSUE THREAD

**Issue by zakius** [SmartRSS/Smart-RSS#112]

**Comment by atomGit** [comment]
unless there's any objections, perhaps print functionality could be removed for simplicity's sake? who prints anything these days, and if this is needed, content can always be copied to a text editor

**Comment by zakius** [comment]
Actually I disabled it to make migration to template-system-less easier, nobody complained about this issue nor about it getting disabled so it is low priority but I still think it may be worth keeping this functionality
