### ISSUE TITLE
SRSS removed from AMO - why?

### ISSUE THREAD

**Issue by atomGit** [SmartRSS/Smart-RSS#115]
i was just going to run a test on a fresh profile and i see SRSS has been removed from AMO - what's up?

**Comment by zakius** [comment]
someone decided to finally perform manual check and decided I can't use template system as is, I'll fix it as soon as possible

**Comment by atomGit** [comment]
congratulations :)

i hope getting relisted wasn't too much of a hassle

**Comment by zakius** [comment]
Thanks
I had to find motivation first, for now I took some shortcuts so code is pretty messy but at least I could publish it again, I plan on cleaning it up a bit later, but I'll be pretty busy with work so that will probably wait
