### ISSUE TITLE
Unfortunately unusable slowly on chromium based browsers

### ISSUE THREAD

**Issue by darkarth00** [SmartRSS/Smart-RSS#116]
Unfortunately unusable slowly. Especially when updating feeds and more than 50. Try 100-200 and it is getting more and more sluggish. On Chrome, Chromium and Vivaldi. The same with OPML and SMART.

**Comment by zakius** [comment]
I have identified issue leading to unresponsive behavior during data fetching and published bugfix, it should be available in Chrome Web Store in a few days

Sorry for the inconvenience
