### ISSUE TITLE
What is "New sources found icon"?

### ISSUE THREAD

**Issue by darkarth00** [SmartRSS/Smart-RSS#117]
I just recognize that it turns into the chosen color if I go on some websites. On other ones it stays gray. If I click on the color their is nothing new.

**Comment by zakius** [comment]
Possibly I could word it better, it shows that feeds were found on current website and you can easily subscribe to them by right clicking on the toolbar icon

Probably can consider not showing this icon if you are already subscribed to all found sources/any of them

**Comment by darkarth00** [comment]
Interesting but if I right-click on the toolbar Icon I get the context menu as usual and no adding any feeds.

**Comment by zakius** [comment]
Honestly I haven't tested it in Vivaldi, will take a look

**Comment by darkarth00** [comment]
Tested on Google Chrome and it works well. So it's an specific vivaldi problem in the first place. Which doesn't suprise me because the individualisation is on a very high level.

Don't know if you can fix that. Would be nice if...  but it's not a problem if not because I can still do it manually.
 
But if it's not possible to fix I would like to see an option to deactivate the "source search" because  the "color for nothing" effect irritates me everytime again. :D

**Comment by zakius** [comment]
I contacted Vivaldi about this issue

I have few ideas how to improve the detection mechanism UX in the future, but as mentioned in your another issue I have to delay these changes

**Comment by darkarth00** [comment]
No prob. Thanks for your time and efforts.

**Comment by zakius** [comment]
I implemented some feed detection quality of life changes:

you can decide when icon should change (any feeds detected, any not subscribed feeds detected, only not subscribed feeds detected, never), if already subscribed feeds should be listed (still won't work on Vivaldi most likely though, got no response in that matter) and ability to skip most of the process if you don't need/can't use feed detection.

I'll upload new version if a few minutes and it should be available in few hours at most

**Comment by zakius** [comment]
just for heads up: in Vivaldi 3.1.1929.34 the subscription menu is available, probably it was fixed earlier but I don't use the extension there
