### ISSUE TITLE
Feature Requests: Selection Window for "open feeder options" & "unread feeds only" page

### ISSUE THREAD

**Issue by darkarth00** [SmartRSS/Smart-RSS#118]
On the older Versions: If there were unread articles and you clicked on the Icon it showed you only the unread ones and the read ones were hidden. And if there were no unread articles it showed you all feeds. Now it shows you nothing or "all feeds". Depends on some option you can make.

I would like to get this "open feeder with unread only" back because I'm using smartrss for youtube and twitch and it often happens that release dates and adding feed timepoint are not the same. Which causes that unread article can be far below if you open "all feeds" because they are one day older or something. Especially when livestreams are over and getting uploaded automaticly by the platforms.

By the way "Select first article on feed selection" is working only when "Select all feeds on reader open" is activated. 

So I guess it would makes sense to integrate a selection window called like "open feeder with" where you can choose between "all feeds", "only unread feeds", "first article", "no selection".

Another nice option would be to add a page between "all feeds" and the first feed where you get  unread feeds only.

Maybe both if it's possible.

**Comment by zakius** [comment]
For the first point you are second person mentioning it but it never really worked this way (I even went through code history to make sure), you can click on the unread counter or alt+click the source to display unread only, I hope this will suit your needs


I won't be adding anything in the foreseeable future as I have to fix one big issue before resubmitting to AMO, I'll only get back to developing once I get that done, may get some bugfixes done in the meantime though

**Comment by darkarth00** [comment]
Ah.. didn't know about that function. Thanks for that info. Suit it very well.
