### ISSUE TITLE
Settings are reset to their defaults on browser opening

### ISSUE THREAD

**Issue by joberreiter** [SmartRSS/Smart-RSS#122]
After the update to 2.16.2, settings have been reset to their defaults.
Additionally, changing settings does only work until the browser is restarted -- settings are back on their defaults on every opening of the browser.

SmartRSS v2.16.2 
Waterfox Current 2020.06 64bit

**Comment by joberreiter** [comment]
May be related to #121 ... ?

**Comment by zakius** [comment]
Thanks for the report, for some reason once in a while settings are not loaded from store properly, though it never happened in my main profile on Waterfox Classic, only in Firefox Quantum.

I'm looking into this now

**Comment by zakius** [comment]
version 2.16.4 I just uploaded to AMO hopefully will fix this issue, unfortunately I can't be sure as I can't reliably reproduce it, it sometimes just happens.

Leaving this open just in case

**Comment by joberreiter** [comment]
Seems that the settings are now stored.

Still have >33000 articles unread (it were about 20 yesterday) and the pinned entries are gone. But that is not a serious problem for me. 

Anyway, I have noticed that the setting field "User CSS" has (or has now) the following content: 

`:root {

  --blue-40: #45a1ff;
  --blue-50: #0a84ff;
  --blue-50-a30: rgba(10, 132, 255, 0.3);
  --blue-60: #0060df;
  --blue-70: #003eaa;
  --blue-80: #002275;
  --blue-90: #000f40;

  --grey-10: #f9f9fa;
  --grey-20: #ededf0;
  --grey-30: #d7d7db;
  --grey-40: #b1b1b3;
  --grey-50: #737373;
  --grey-60: #4a4a4f;
  --grey-70: #38383d;
  --grey-80: #2a2a2e;
  --grey-90: #0c0c0d;

  --white: #fff;
}`

I do not remember that I have entered this ... should it look like that?
Note: Trying to reset the style, nothing changes, still there.

**Comment by zakius** [comment]
I'm sorry for these duplicates articles, intended to perform one time UID update but when settings failed to load it was modified again and again so items already in storage weren't recognized. Unfortunately I can't clean up automatically as there's no way of telling which items are relevant for user

This style is default value provided for simplicity, just custom properties used across the stylesheet so if someone wants to change colors only it's much easier

I probably should increase the size of textarea and provide this detail somewhere, maybe default to blank and provide another button to fill with this one?

**Comment by joberreiter** [comment]
> I'm sorry for these duplicates articles, [...]. Unfortunately I can't clean up automatically as there's no way of telling which items are relevant for user

I suspected it --- as I said, not really a problem for me. 

> I probably should increase the size of textarea [...]

I agree at the textbox size, it is tiny.

> [...] and provide this detail somewhere, maybe default to blank and provide another button to fill with this one?

Or fill in the default but add comments to the style template itself?
e. g. like

`/* Default color template; for easy change of colors */
:root {
--blue-40: #45a1ff;
--blue-50: #0a84ff;
....
`

**Comment by joberreiter** [comment]
I close the issue.
