### ISSUE TITLE
Feed pane: folder properties do not open

### ISSUE THREAD

**Issue by joberreiter** [SmartRSS/Smart-RSS#123]
Right clicking a folder in the feeds area shows up a context menu (Update, Mark all..., Delete, Prop
erties).

![2020-06-20_120428](https://user-images.githubusercontent.com/13220647/85199238-46529800-b2ee-11ea-806a-211b11ed1767.jpg)

Clicking on the last entry "Properties" is not  possible / does not trigger anything.

**Comment by zakius** [comment]
I'll look into this soon, probably is caused due to removal of existing templating system to satisfy AMO requirements

**Comment by zakius** [comment]
Fixed in 2.17.0
