### ISSUE TITLE
feed properties 'autoremove' and 'parent' reset to 'mixed'

### ISSUE THREAD

**Issue by atomGit** [SmartRSS/Smart-RSS#125]
SRSS 2.16.4 (and possibly 1 previous version)

the 'autoremove' property for all my feeds has been set to 'mixed' somewhere along the line - it should be 'never' i believe

also i don't see any article purging options in the settings, so i'm bewildered as to why 'mixed' is being displayed, as though there were global and individual feed options

i know you said the code was a little messy right now as a result of the AMO deal, so maybe that's the reason

**Comment by zakius** [comment]
That should be fixed in 2.17.0 I just published, it indeed came from changes in interface rendering, once I got to it I rushed it a bit too much

**Comment by atomGit** [comment]
and indeed it is - thanks!

**Comment by AtTheGates** [comment]
Sorry for posting in a closed issue, but I have a question regarding the "autoremove" property: Are only read items removed (what I would prefer)? Or read AND unread?

Control "autoremove" as global would be nice in the options/ settings page. :-)

**Comment by zakius** [comment]
All of them are moved to trash and I think the date of creation is taken into account, as I never used this feature I'm not sure if it makes any sense to be honest

If you have any suggestions how I can improve it feel free to submit a new issue
