### ISSUE TITLE
Feature request: "Autoremove" - keep unread articles

### ISSUE THREAD

**Issue by Haven667** [SmartRSS/Smart-RSS#127]
I'm an old [**NewsFox**](http://newsfox.mozdev.org/index.html) user (pre-Quantum). There was an option to delete old articles automatically (like "Autoremove" in **Smart-RSS**), but keep unread ones. See the options dialog screenshot:

![newsfox_keepunread](https://user-images.githubusercontent.com/9346225/85545896-add55400-b61c-11ea-9535-44d8ef28b6c6.png)

This would be great for **Smart-RSS**. But if it's not important for you or difficult to realize, I could understand it. Thank you in advance. :-)

**Comment by zakius** [comment]
Making it configurable definitely sounds like a good feature and I'll most likely add it, but I can't tell you any ETA right now, will decide on my next priorities once I get some time to take a look at issues and things I have on my mind

**Comment by Haven667** [comment]
Thank you so much (also for the other work on this extension). It works like a charm. Happy new year! :-)

**Comment by Haven667** [comment]
I'm sorry. I was too hasty. "Auto remove" doesn't work for me correctly, if I configure it in the settings under "Behaviour". I tested it with a new clean profile (without other extensions and modifications).

When I install the extension and configure the "Auto remove after" to one of the "Older than" settings, set "Auto remove" to "Keep unread", add feeds to it and check for updates, ALL feed entries get deleted. Also the unread ones.

It works, when I right click every feed in the list and configure it via "Properties".

Windows 10, Firefox v84.0.2, Smart RSS Reader v2.22.0

**Comment by Haven667** [comment]
Hi,

the "Keep unread" function works as aspected now in global mode. But ALL read entries get removed also. Even these, that are not older than (for example) 1 week. Is this behaviour intended?

My goal/ wish would be to remove read entries, that are older than 1 week, but to keep unread ones and read ones, that are not older than 1 week.

Thank you very much in advance. :-)

Windows 10, Firefox v87.0, Smart RSS Reader v2.22.2

**Comment by zakius** [comment]
I'm sorry for the trouble, found issue with reading the removal delay from settings and will release the fix soon

**Comment by Haven667** [comment]
Hey zakius,

no need to sorry. Just take your time, whenever you have. I'm so thankful for your work.
