### ISSUE TITLE
Feature request, reset, backup, import settings

### ISSUE THREAD

**Issue by gabri25ele** [SmartRSS/Smart-RSS#128]
I would like an option to reset, backup, import settings if possible.
Or at least know where the settings file is located in the firefox profile, because uninstall extension, not delete the settings.

**Comment by zakius** [comment]
with WebExtensions API there is no reliable filesystem access so there is no file anywhere, everything is stored in various storages, in case of this extension it is IndexedDB, you can preview that data by inspecting the extension but can't really manage it

Settings are pretty easy to recreate so I never bothered with exporting and importing them but I do see it may be useful sometimes and will add this feature

As of backup, due to API limitations I don't think I can build reliable automated mechanism unfortunately but once I build the setting import/export you'll be able to make manual backups.

And everything else can be exported and imported already, in case you missed that

**Comment by gabri25ele** [comment]
I would like to delete all the settings beacause when I imported my profile in a new Firefox folder, the SmartRSS blocked itself and Firefox... maybe there was too many "unread" (About 5000).
The only solution I have found is to restart from 0.
it would have been useful to be able to delete the file containing the subscribed feeds.

**Comment by zakius** [comment]
with a big backlog I suggest unchecking `Select all feeds on reader open:`

importing such a batch may cause few minutes of slowdown, I recommend performing the import then leaving Smart RSS to do its thing for a while before opening reader, it should be fine once icon stops animating (at least if you have mentioned option disabled)

And honestly I don't see how importing, exporting and resetting settings would affect this issue in particular


that said, if the slowdown/lockdown happened in different scenario I'd be grateful if you shared detailed steps to reproduce as import alone shouldn't cause this even with gigantic backlog

**Comment by gabri25ele** [comment]
I have already unckeched **Select all feeds on reader open** from ever.
It was not a problem to import feed (in the example previous), in fact I have solved with reimporting... 
the problem was to delete all feeds without smartrss page working.

**Comment by gabri25ele** [comment]
see that example

![sshot-1](https://user-images.githubusercontent.com/33927879/87147195-7f0ddd80-c2ac-11ea-9822-8542a8ae5cf0.png)

Firefox portable, Smart RSS is blocked. Only way delete all RSS (uninstall addon) and reimport list.

**Comment by zakius** [comment]
yeah, as I said in this case you should avoid clicking `all feeds`, in most cases it will unlock after a while but it's not worth it

I'll try to figure out a way to not load lists as big as this at once at all so it won't lock up like that too

**Comment by zakius** [comment]
I just pushed change that should prevent main thread locking while rendering long lists so if you are able to build extension yourself you are welcome to test it, signed package should be available on AMO in a few days with some other upcoming changes including settings import/export/reset you requested

**Comment by gabri25ele** [comment]
> yeah, as I said in this case you should avoid clicking `all feeds`, in most cases it will unlock after a while but it's not worth it

Anyway I didn't click on nothing, when I opened Smart RSS... it does it all!
Thanks for the update. In this momento I don't have problem, so I'm waiting without problems :)
