### ISSUE TITLE
sorting by title again does not work.

### ISSUE THREAD

**Issue by rubel-22** [SmartRSS/Smart-RSS#129]
In the 2.17.0 release, sorting by title again does not work. All news headlines are displayed in shuffle.

**Comment by zakius** [comment]
I cannot reproduce this issue, can you find exact steps?

**Comment by rubel-22** [comment]
I just put version 2.17.0 on top of 2.14.2 and all news headlines are displayed in a jumble at once

**Comment by zakius** [comment]
I see

Do you by any chance have both primary and secondary sorting set to Title? I'm not sure why that happens but if you have secondary sort set to Title and then set primary one to title too it freaks out, I'll look into this. If that's the case for you I suggest setting secondary sorting to something else in the meantime
