### ISSUE TITLE
View the feed in the viewport.

### ISSUE THREAD

**Issue by rubel-22** [SmartRSS/Smart-RSS#131]
I was wrong, sorry

**Comment by zakius** [comment]
I had this issue for a while and while I did what I could to fix it I'm not sure if it doesn't happen in some specific flow, if you happen to encounter it please try to ind a detailed way to reproduce

**Comment by rubel-22** [comment]
This bug was in version 2.14.2.
Now I updated it to 2.15.2, it became normal.
I would also like to have a context menu in the properties of the feeds, please.
