### ISSUE TITLE
2.18.0

### ISSUE THREAD

**Issue by rubel-22** [SmartRSS/Smart-RSS#137]
In the new version smart_rss_reader-2.18.0, sorting by news headline still does not work.
And the icons of many feeds are not displayed, for example:
https://www.gazeta.ru/export/rss/lenta.xml
https://sobesednik.ru/rss.xml
http://rss.ru-board.com/rss.cgi?30
http://riperam.org/feed.php?mode=torrents
http://feed.rutracker.cc/atom/f/9.atom
and others.

**Comment by zakius** [comment]
Now I can't replicate the issue with sorting at all, it just works for me
I'll look into loading favicons

**Comment by rubel-22** [comment]
The sorting problem looks like this:
In the extension settings, I set sorting by news headline, switch to view, everything is OK, sort by headline. Then I close Firefox, open Firefox again and see that sorting by title has broken, I need to set sorting by title again in the settings. And so on until the next Firefox closure. This is how this bug looks for me.

**Comment by zakius** [comment]
okay, I'll look into this, thanks for additional details
