### ISSUE TITLE
[feature] xml preview

### ISSUE THREAD

**Issue by atomGit** [SmartRSS/Smart-RSS#138]
sometimes it's nice to see what articles the feed contains in before deciding whether to subscribe and since the feed preview function was removed by the geniuses at mozilla, it would be great to have this back and would complete the feature set i think (and avoids having to install yet another extension)

if this gets added, i would suggest changing the behavior of the feed detection icon to where a primary/left click open a menu containing the available feeds - after clicking one, the preview is shown with a 'Subscribe' label/icon/link

[rsspreview](https://github.com/aureliendavid/rsspreview) seems to do a pretty good job and maybe could provide sample code

ps: the 2.18 update was quite impressive - thanks much for your work!

**Comment by zakius** [comment]
I'm leaning towards scrolling freshly added feed into view so you can easily remove it, it would add much less complexity to the code, especially when you take in count edge cases spread between Chromium, Quantum and pre-Quantum browsers.
Unfortunately that isn't trivial either

**Comment by atomGit** [comment]
sounds reasonable

**Comment by zakius** [comment]
I've been digging into this a bit but can't make source scroll into view reliably after it loads and sorts without bigger changes, will be stalling this and may get back to it later.

For now there's a simple workaround of manually scrolling when freshly added feed loads if you want to remove it after all. And now that I think about it I'll add `remove selected feed` button to sources toolbar probably to make it easier
