### ISSUE TITLE
Settings don't work

### ISSUE THREAD

**Issue by darkarth00** [SmartRSS/Smart-RSS#144]
Hello,

today I recognized a new design for the settings. It's Version 2.20.0.

I can open the setting tabs on the arrows but smart rss doesn't react to setting changes in any way. I also cannot export or import any of my feeds anymore.

I'm using windows 7 64-bit and the newest version of vivaldi.

Best regards

**Comment by zakius** [comment]
Sorry for trouble, this issue will be fixed in the next release, depending on Chrome Web Store approval should be available in few hours up to few days
