### ISSUE TITLE
endless feed update

### ISSUE THREAD

**Issue by agafron** [SmartRSS/Smart-RSS#150]
this feed https://petition.president.gov.ua/petition.rss updating infinitely
![Захват экрана_Выберите область_20210120000743](https://user-images.githubusercontent.com/26525518/105098975-8e6bb000-5ab3-11eb-8749-893d19c429b9.gif)

**Comment by zakius** [comment]
It looks like issue with internal favicon parser, seems to get stuck on error instead of just placing placeholder icon there

If you don't care about using external provider you can switch it in settings for the time being while I take care of it

**Comment by agafron** [comment]
>>If you don't care about using external provider you can switch it in settings
It`s works, thanks!!!
