### ISSUE TITLE
Content has wrong height on some feeds

### ISSUE THREAD

**Issue by nijssen** [SmartRSS/Smart-RSS#151]
The sandbox frame is too short on some feeds, making it so that I cannot see much of the text without opening the item's link.

Example below, from [this feed](https://blogs.msdn.microsoft.com/oldnewthing/feed): 
![image_2021-01-19_152814](https://user-images.githubusercontent.com/1368382/105106541-f21dbb00-5a6a-11eb-84b1-a207e5dcf0a1.png)
As you can see, there is a scrollbar, but it won't go down far enough. The `smart-rss-content-footer` cannot be scrolled into view.

This has been happening in all versions of this extension. Curiously, this bug does not happen on the old extension (that this one is forked from)

My hypothesis is that the height calculation isn't working properly. However, I am not sure how to fix it.

I am using Opera 73.0.3856.284.
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284.
Also reproducible in MS Edge.

Another feed that exhibits the same problem: [this one](http://emojiwrap.com/issues.rss) with item guid `https://emojiwrap.com/issues/43` (yet other items from the same feed seem to work fine).

**Comment by zakius** [comment]
I changed a lot of things in the content view to extend it's capabilities but my testing on Chromium wasn't extensive enough it seems, I'll take a look at this, but it may take a while

**Comment by nijssen** [comment]
Forgot to mention this when you released the new version but just want to report that it totally works now! Thanks again
