### ISSUE TITLE
Infinite rss feed update

### ISSUE THREAD

**Issue by Lapinmagique** [SmartRSS/Smart-RSS#154]
Since the last update, I have a lot of feeds that are in infinite "reload" and that it does not stop, even with a refresh of the rss feed, it remains like this

_sry for bad english, I use google translator_

![image](https://user-images.githubusercontent.com/43154248/105613304-f545dd80-5dc1-11eb-9685-ca7d7ac55b24.png)

**Comment by zakius** [comment]
As mentioned in #150 it's issue with favicon loading, I fixed it already but have to take care if some other things before I release it, in the meantime you can change favicon service to external if you don't mind it
