### ISSUE TITLE
Feature Request: Add toggle for "Show only unread articles" to toolbar of the article list

### ISSUE THREAD

**Issue by Bbansjkl** [SmartRSS/Smart-RSS#155]
I've noticed through #108 that there's an option to display only unread articles in the article list by holding down the "alt" key when selecting a feed. Holding that key down every time a feed is selected gets cumbersome pretty fast, so I'm proposing to add a toggle for this behavior in the toolbar of the article list.

**Comment by zakius** [comment]
Sorry for late response, I'll probably take care of this but I have to prepare icon that would make sense for this, I can put something temporary there but that's less than ideal

**Comment by zakius** [comment]
Okay, this proven to be much more tricky than I anticipated so I'll be getting back to it at a later date. I did some work already but can't put the button on toolbar until I get it filter the already displayed list on the fly
