### ISSUE TITLE
Ars Technica feed not being parsed?

### ISSUE THREAD

**Issue by OscarL** [SmartRSS/Smart-RSS#158]
I've tried to add the following feed:

    http://feeds.arstechnica.com/arstechnica/index

It works for me in Opera Mini's RSS reader, but when I add it to SmartRSS, it does not parses it Title, nor articles (0 unread, 0 total).

Not sure if this is a standard compliant feed or not, but as it works in other readers, might as well report it here.

Thanks a lot for your work! I think I finally found my Google Reader replacement after all these years! :-)

**Comment by zakius** [comment]
it's likely issue with favicon loading, I'll soon release the bugfix but in the meantime you can use different loader as when it happens everything gets stuck

**Comment by zakius** [comment]
Does it seem like feed parsing in general stops working when you add it? If so it's issue with favicon loading I have already fixed internally, in the meantime you can change it to external in settings if you don't mind sending addresses of homepages you read periodically to external service. I'm sorry for delayed release of the said fix

**Comment by OscarL** [comment]
I've just installed version 2.22.2, tried to add the feed mentioned above, and Smart-RSS add an entry to the list of feeds (with the given url unchanged), but it doesn't shows anything (no content, no list of entries).

**Comment by zakius** [comment]
I'll take deeper look into this

**Comment by zakius** [comment]
I just checked it both in Waterfox Classic and Nightly and loads just fine and instantly, can you check it in new browser profile?

**Comment by OscarL** [comment]
I've just tested with Firefox 87. Created a new profile, switched to it, installed Smart-RSS, added the Ars-Technica feed...

It just worked flawlessly.

I guess I'll close this issue as invalid then.

Can you think of anything I could check to see why it doesn't works on my default profile? If not, don't worry, I don't want to make you loose any more time with this than I already have.

Thanks a lot for your work on this addon.

**Comment by OscarL** [comment]
I just found out what the issue is.

I just changed this setting: `dom.security.https_only_mode` from `True` to `False`, added the feed for Ars, and it worked right away.

Somehow I missed the fact that Ars doesn't seems to provide HTTPS support for its feed.

Well, at least I now know WHY it wasn't working.

Thanks again for your work and time!

**Comment by zakius** [comment]
thanks for the update!

at this point I assume we should ping them to update their links in layout, if I find some proper contact will do and I encourage you to do the same

**Comment by OscarL** [comment]
I've just sent them a message from their online contact form: https://arstechnica.com/contact-us/ to their "404/Missing/Incorrect URL" department.

Thanks again @zakius!

**Comment by markcellus** [comment]
@OscarL were you able to get this working? If not, Open RSS supports Ars Technia RSS feeds for home page and section pages, all with full text of article:

https://openrss.org/arstechnica.com

**Comment by zakius** [comment]
I completely forgot about this issue, they still haven't fixed their links? That's amazing in a way...
Unfortunately I have very little time to work on this project anymore and knowing it will all get destroyed when Mv3 becomes mandatory makes it even harder to push myself so I mostly take care of personal annoyances and not necessarily release these changes due to little time to test them properly
