### ISSUE TITLE
infinite update on a specific RSS

### ISSUE THREAD

**Issue by gabri25ele** [SmartRSS/Smart-RSS#161]
I have an endless update on this RSS. 

![infinito](https://user-images.githubusercontent.com/33927879/112457029-a1248e80-8d5b-11eb-926b-5549b6c0b0d6.png)

Could it be that the problem is with Smart RSS? 
I tried another extension and it doesn't happen.

**Comment by gabri25ele** [comment]
closed without an answer?

**Comment by zakius** [comment]
1. it was answered multiple times

2. fix is released

**Comment by gabri25ele** [comment]
1. but where?
2. we pray for it 🙏
