### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by woldy62** [SmartRSS/Smart-RSS#163]
Could you make it possible to include a dark theme?
I played with RGB colors in User CSS, but it turned out ugly. The main text of the article does not change at all from black.

**Comment by zakius** [comment]
By myself I am unable to provide a decent new theme, but I will look into theming the article view to see if there's something wrong with it and how to fix it when I find some time

**Comment by woldy62** [comment]
Thanks for the answer. Do as you see fit. I meant the subject as in this fork: [https://chrome.google.com/webstore/detail/the-rss-aggregator/ffhafkagcdhnhamiaecajogjcfgienom](url) 
Look at the screen: [https://i.imgur.com/umo7lwE.png](url)

As for the number  **#65**, I will definitely look at it.  Thanks.

**Comment by zakius** [comment]
It may be really early fork but also just a separate project, there's a vast difference between it and current state of Smart RSS for sure. But to the point: I can add a little toggle allowing color inversion like in this extension and workarounds for content images and favicons, can't promise much more

**Comment by woldy62** [comment]
That would be great for me. Thank you in advance. 

By the way, when I turn on the Force Dark Mode for Web Contents flag in Chrome (Center Browser), I get a good result (screen).
But this mode is not liked on other sites...
Screen:   https://i.imgur.com/Iq5VKWL.png

**Comment by zakius** [comment]
Implemented in Master, will be available in next release
