### ISSUE TITLE
Support browser synchronization to synchronize feeds

### ISSUE THREAD

**Issue by skobkin** [SmartRSS/Smart-RSS#165]
What do you think about using browser synchronization feature to keep feeds (and their settings) in sync between all machines?

No need to sync the content itself, but at least sync the feeds.

Synchronizing read/unread state is another level of the feature implementation that would be good to have.

**Comment by zakius** [comment]
amount of storage available to extensions sync is too low even for that as far as I can estimate, it would only work in scenarios when your sources list is so small it doesn't really matter, sorry

**Comment by skobkin** [comment]
Thank you for clearing that up. Looks like I need to consider using self-hosted solution like ttrss.
