### ISSUE TITLE
Regarding manifest v3

### ISSUE THREAD

**Issue by zakius** [SmartRSS/Smart-RSS#167]
Most likely I will be unable to port this extension to Manifest v3 format so once that becomes the only option in your browser it won't work anymore. This is caused by multiple smaller issues, some of them being: 
- I'm not interested in actively supporting Chromium at this point, if it works it works, if it can be easily fixed I can spend some time on it, but that's not in my personal interest
- I'm also not interested in supporting Quantum at this point, though it's less likely to break as I'm developing in it but my daily driver is pre-Quantum so I may miss some issues happening in newer versions
- code used in background is massive and built assuming it's running all the time, keeping the collection and settings in memory all the time which is impossible with event driven service worker
- communication between the view and background isn't done using messaging but by direct access of background page `window` in most cases
- I taken over this project to make a tool for my personal use and decided to share if in case anyone else benefits from it, but my personal needs are the highest priority
- I rarely have motivation to do big batches of coding and porting this project would require that
- and when I have that I'd rather use it on another project I have in mind

there's still a lot of time before Manifest v3 becomes mandatory and the list above may become invalid in the meantime, but if anyone is wondering right now that's my stance as of today, if anything changes I'll update this issue

**Comment by zakius** [comment]
few updates:

- I'm using Quantum based browser for some time now and while it's annoying to fix some issues every now and then it'll stay like that as long as Mv2 extensions are supported, but that point in time isn't well defined by Mozilla
- besides the points stated before fulltext search, or search at all, to my knowledge would be impossible to implement efficiently with Mv3 due to lack of SQL database, and performing in-memory lookup like now would be too costly due to need to load the whole store into memory for every search first (if you know any other workaround let me know, I *may* decide to create a new extension at some point)

**Comment by atomGit** [comment]
hi @zakius - i hope you'll keep us posted as to what your plans are - i prefer your extension over all others and while i hope you keep working on it, i will of course understand if you decide to drop it

**Comment by zakius** [comment]
sooner or later it will just stop working, fortunately Google is constantly pushing away sunsetting Mv2 and Mozilla surely won't do that earlier, but it's going to happen and there's no way for me to update this codebase to work on Mv3

I'm sure I'll figure something out for personal use, but it's hard to say whether it'll be useful for anyone else, honestly don't see any way of doing it without help of external software running outside of the browser, but as new API emerge it may change

**Comment by zakius** [comment]
I stopped using this extension a while ago as I moved to a selfhosted solution, I'm spending most of my non-professional coding time working on it currently, I would not expect myself to touch this project again as it's ancient, built in different age and honestly a pain to work with. There are some elusive bugs I am aware of but was never able to properly understand and other issues like that. With enough effort it very likely could be fixed, cleaned up or even migrated to Mv3 (using things like dexy), but I am not the person that will do this, I'm sorry

**Comment by atomGit** [comment]
thanks @zakius - and good luck in whatever you do

thanks for maintaining this project for as long as you have
