### ISSUE TITLE
Issues with youtube feeds

### ISSUE THREAD

**Issue by akizuha** [SmartRSS/Smart-RSS#168]
1. If the `url` has `-`, the media preview will not display correctly. `url` after `-` is truncated.
2. Line endings in `media:description` are not treated. Maybe replace with `<br>`?
3. Also, it would be nice to have an option just display a thumbnail rather than a whole embedded player (slow).

**Comment by zakius** [comment]
I'll evaluate 3, for 1 and 2 I'll need more details, can you provide some samples?

**Comment by akizuha** [comment]
From feed: https://www.youtube.com/feeds/videos.xml?channel_id=UCgFvT6pUq9HLOvKBYERzXSQ
Entry: Goodbye.

# Display:
![img0](https://user-images.githubusercontent.com/45957847/120012646-5a306f00-c012-11eb-8adc-36b721acd6e6.png)

# HTML:
## Preview section:
![img1](https://user-images.githubusercontent.com/45957847/120012472-248b8600-c012-11eb-90bd-c2d07b1b2c33.png)
## Description section:
![img2](https://user-images.githubusercontent.com/45957847/120012781-88ae4a00-c012-11eb-8b6e-2a389dea6d90.png)

# Original youtube page description:
![img3](https://user-images.githubusercontent.com/45957847/120012876-a8de0900-c012-11eb-821e-364203ea7faf.png)

**Comment by zakius** [comment]
thanks, I'll look into this

**Comment by akizuha** [comment]
## Fix for 1,3
https://github.com/SmartRSS/Smart-RSS/blob/7cc876d467338a8d8059dff2a4c129ee32c21e9c/src/scripts/app/views/contentView.js#L241-L248
```
                            case 'youtube':
                                const videoId = /^.*\/(.*)\?(.*)$/.exec(data.enclosure.url)[1];
                                if (false){ // need to add an option
                                    enclosure = document
                                        .createRange()
                                        .createContextualFragment(enclosureYoutube);
                                    const iframe = enclosure.querySelector('iframe');
                                   iframe.src = `https://www.youtube.com/embed/${videoId}`;
                                } else {
                                   enclosure = document
                                       .createRange()
                                       .createContextualFragment(enclosureImage);
                                   const img = enclosure.querySelector('img');
                                   img.src = `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`;
                                   img.alt = videoId;
                                }
                                break;
```

# Fix for 2
https://github.com/SmartRSS/Smart-RSS/blob/7cc876d467338a8d8059dff2a4c129ee32c21e9c/src/scripts/app/views/contentView.js#L319
```
                        var fragment;
                        switch (data.enclosure.medium) {
                            case 'youtube':
                                fragment = document.createRange().createContextualFragment(content.replace(/\r/g, '<br>'));
                                break;
                            default:
                                fragment = document.createRange().createContextualFragment(content);
                        }
```

**Comment by zakius** [comment]
thanks for your contributions, I'll take a look at them when I find some time, though for the slowness I had loading player on demand in mind so you don't lose ability to play video inline
