### ISSUE TITLE
toolbar redundance

### ISSUE THREAD

**Issue by akizuha** [SmartRSS/Smart-RSS#169]
![img](https://user-images.githubusercontent.com/45957847/119970948-ef1b7400-bfe2-11eb-8bd5-031620449ef3.png)

These two buttons do the same thing. So I suggest to change the left one to `Mark All As Read`.

**Comment by zakius** [comment]
I *may* make it optional as I don't want to break flow and cause unexpected behavior for people who actually use the left one, this should be small enough to be reasonable, but I can't give you any ETA

**Comment by akizuha** [comment]
Sure, an option is sufficient, thanks for your reply.
