### ISSUE TITLE
Fetching Full Article

### ISSUE THREAD

**Issue by akizuha** [SmartRSS/Smart-RSS#171]
Some feeds only gives a small part of the beginning of the article or piece of summary. Hope SmartRSS can fetch the full article by it self like Firefox's reader mode. Could get away with a lot of undesired ads, pop-ups or disturbing elements of viewing the original page.

**Comment by zakius** [comment]
I've been looking into this a bit and found few potential libraries I could use but can't promise anything, to be honest it's unlikely I'll do this as per #167

**Comment by akizuha** [comment]
Wish I can help. Since this is the best RSS add-on I can find on AMO.

**Comment by zakius** [comment]
thanks for your kind words, though the part of code where changes have to be applied is especially convoluted to workaround multiple issues with `iframe` size not reflecting the content if images load slowly, handling id targeted anchors and many others so it'll be complicated and may end up breaking something, if I get some time after fixing issues I'll see how much actually has to be done to make it work

**Comment by zakius** [comment]
I just added the same parser Mozilla uses for their reader view, will be test driving it for next few days while I work on other issues. Obviously it has all the same limitations like it's unable to process multi page articles, I'll be looking for solution that can handle it as an alternative
