### ISSUE TITLE
same embedded video copied to multiple articles

### ISSUE THREAD

**Issue by atomGit** [SmartRSS/Smart-RSS#176]
when an embed is contained in the article, it may be reproduced multiple times for any number of other articles which are displayed in the preview pane

see image [1](https://i.postimg.cc/cH88pTCC/1.png), [2](https://i.postimg.cc/Pq7wV0t0/2.png), [3](https://i.postimg.cc/9f09pcjG/3.png) (images will be deleted in 31 days)

**Comment by zakius** [comment]
can you share the feed address?

**Comment by atomGit** [comment]
i neglected to note the address and i can't reproduce the issue at the moment - the next time it happens i'll report back

on another (completely different) note - i encourage users of github to boycott the platform as it is continually becoming more of a shit-hole since micro$oft's acquisition, a company that violates everything that free software stands for - please consider a more ethical, unobtrusive platform such as [Codeberg](https://codeberg.org/Codeberg/Community/issues)

**Comment by zakius** [comment]
From pragmatic point of view GitHub doesn't negatively impact me personally and allows much better discoverability and less friction for users who want to contribute as they most likely already have an account so at this point in time I'm not interested in migration, but if anything I find disturbing happens I'll definitely consider alternatives

**Comment by atomGit** [comment]
title of this issue should probably be changed since the issue can occur with images as well

at some point while reading news [this image](https://i.postimg.cc/rpYZ65pf/rss-reader.png) was in one of the posts, probably as a 'featured image' (i watch over 200 sites so it's difficult to track down the origin)

after that, the same image was used as the feature image again in many following posts,  however **there may be a common thread here in that each post that was affected is from the same domain** - i could not reproduce this when viewing feeds from any other domain

example posts which all used the same featured image in the reader...

https://www.theepochtimes.com/over-800-unaccompanied-children-crossing-border-illegally-apprehended-in-one-day_3938066.html

https://www.theepochtimes.com/police-shoot-armed-13-year-old-boy-who-falsely-claimed-he-killed-3-people_3938130.html

https://www.theepochtimes.com/nyc-officials-and-small-businesses-object-to-proof-of-vaccination-mandate_3936650.html

https://www.theepochtimes.com/california-republican-party-wont-endorse-candidate-in-recall-election_3938110.html

https://www.theepochtimes.com/160-san-francisco-sheriffs-deputies-threaten-to-resign-due-to-mandatory-covid-19-vaccine_3938032.html

etc....

**Comment by zakius** [comment]
okay, so what I managed to figure out for now: ~this feed~ *randomly selected feed from this website* serves multiple enclosures for some of articles, first one being *the same* video, so something is broken on their side for sure (not to mention it's advised to not serve multiple enclosures, but I have issue to support that as #174 as there are usecases for that, but I have to think about that more)

so there are two things: first of all I'd suggest you report that issue to the website admins and second, I probably will implement support for multiple enclosures at some point, but that asks for in depth analysis of what I can and should do

**Comment by zakius** [comment]
taking in count one part of this issue is already tracked and other is problem with feed itself that I can't fix (and I'd prefer to not include exceptional handling to work it around) I'll close this now
