### ISSUE TITLE
Help with the user CSS block in settings

### ISSUE THREAD

**Issue by via80HD** [SmartRSS/Smart-RSS#177]
Howdy, I didnt know where else to go to ask (i searched around google and what not and couldn't find anything to really help me}
So I guess for starters I ought to make sure the CSS box is for tweaking the theme a little bi ie the colors and what not? Thats what I currently understand it to be but Im not 100 percent sure, Im kinda just guessing with this so maybe Im wrong

If it is for changing colors and what not could you please tell me where I find some help on it? I have tried just simply changing up the numbers but it didnt make any changes at all. I was just trying to mess around and change up the layout if its possible and cant figure it out. If you know where some instructions are or something i could probably figure it out with a bit of a guide, either way its not a big deal if not. 

Thanks

The css box in settings, the code in the box is what fills in when i click the colors template button.
![rssexterror](https://user-images.githubusercontent.com/84550322/128391519-41e7b30a-c0ba-4411-828a-3fc8fbc5f8a6.png)

**Comment by zakius** [comment]
contents of this block get attached after the main style sheet, the colors template uses custom properties to make it easier to change colors, you can read up on them more here https://developer.mozilla.org/en-US/docs/Web/CSS/--* but you can paste there basically any styles you want

new styles are applied to main reader view once this field loses focus, if that doesn't happen I'll need your browser name and extension version to verify that
