### ISSUE TITLE
Update Bug since the new update

### ISSUE THREAD

**Issue by darkarth00** [SmartRSS/Smart-RSS#180]
Hello,

I'm using Windows 7 64 bit with the Vivaldi Browser.

When I want to update the sources, he always shows all articles as unread that are already in the list. Instead of only showing the new articles as unread.

This happens since a few hours. I saw that today happened an update in smart rss. So it's probably a bug fom that update.

**Comment by zakius** [comment]
Just uploaded a hotfix, it's already available in AMO and should be in Chrome Web Store soon, sorry for the trouble

**Comment by darkarth00** [comment]
It's weird but I still have the issue but only for a specific website (german) and for specific articles from that website. But the articles where this problem is showing up, seem to change, after a few days, too.

At the time, the problem exists for these 3 links: 

https://jpgames.de/2021/08/cyberpunk-2077-die-ersten-dlcs-kommen-und-sie-sind-wie-versprochen-kostenlos/

https://jpgames.de/2021/08/xbox-game-pass-in-der-zweiten-august-haelfte-mit-twelve-minutes-und-diesen-weiteren-games/

https://jpgames.de/2021/08/spike-chunsoft-kuendigt-ai-the-somnium-files-nirvana-initiative-an/


I deleted my browsercache multiple times as well as reinstalled the extension. But that didn't help. I also tested it with the regular current chrome version and the problem showed their up, too. So it doesn't seem to be a Vivaldi problem.

**Comment by zakius** [comment]
for this feed content seems to be dynamically generated for every load and each time some identifiers are changed causing naive string comparison to trigger change detection, I'll try to make it work but when we have also #181 with dateless feeds it gets tricky
