### ISSUE TITLE
article headline not in sync with article preview

### ISSUE THREAD

**Issue by atomGit** [SmartRSS/Smart-RSS#182]
this popped up with the recent update, 2.23.1

in a vertical 3-pane layout, the headline in the center column may not display the correct preview in the right-side column

in the [screen-cap](https://i.postimg.cc/c1MvNyms/smart-reader.png), the headline that is focused (black background) is displaying the text from the headline above - also the title and other metadata is missing

for every article headline clicked below the point where the problem starts to occur, the text in the preview pane never changes

reference: [Naval Inspector General Complaint about UFOs/UAPs/Aliens and Much More – January 2020](https://www.theblackvault.com/documentarchive/naval-inspector-general-complaint-about-ufos-uaps-aliens-and-much-more-january-2020/)

feed address: https://www.theblackvault.com/documentarchive/feed/

**Comment by atomGit** [comment]
downgrading the add-on to 2.0.33 doesn't fix this issue

**Comment by zakius** [comment]
I can't reproduce this, does the issue persist after restarting the browser?

**Comment by atomGit** [comment]
yes

**Comment by michkrol** [comment]
Hi, I'm having the same issue since last update with a different feed: [ArsTechnica](http://feeds.arstechnica.com/arstechnica/index/)

Seems that enabling `Open media preview automatically:` triggers this issue.
