### ISSUE TITLE
[Feature Request] Commandline option for notification

### ISSUE THREAD

**Issue by ghost** [SmartRSS/Smart-RSS#191]
I'm on linux. However, what I'm requesting will be usable on any OS.

The ability to customize a notification to send via terminal/cmd so advanced users can use this for example to get the rss sent to mobile or via email or whatever way they can/want to.

Don't know if the Firefox Extension framework allows this, but would be super cool if its possible...

For example, in transmission bt there is the ability to run a script on task completion and parameters can be passed to the script
![sf](https://user-images.githubusercontent.com/89828026/133914876-bf11cdd7-fa34-4b9c-bc20-1cc37e9acd2f.png)

**Comment by zakius** [comment]
technically it's possible with use of companion app made on purpose to work with an extension, technically you can replace *companion app* of extension with your own one as long as extension actually makes use of one, but that's a bit of fiddling so it would be better if I just provided that too

creative use of well placed manifest file, simple binary or script (example shows python script as the *native app* receiving messages) and that probably would work, though I have to add the messaging code anyway, I'll look into it a bit more and think about consequences of different approaches as it doesn't seem to be hard but it may be more power than I'm comfortable providing if I take the easiest one (type command in extensions > pass it to *native app* > execute it), there are extensions doing just that, but these are built specifically to do that so it's obvious for users while this may seem a bit out of scope for RSS reader, on the other hand if you don't install the companion app nothing can happen to your system so... I just don't know what to do with it at this point

**Comment by zakius** [comment]
I'm sorry, I won't be working on this feature
