### ISSUE TITLE
Favicons Overlapping

### ISSUE THREAD

**Issue by AmmarSaleemG** [SmartRSS/Smart-RSS#198]
Hello, this picture below depicts that favicons overlap on the headline of the article. Secondly, The favicons are not vertically positioned at centre when "Show full headline" is enabled.

![image](https://user-images.githubusercontent.com/15247707/146651321-0ba358fb-aa60-4f4a-906f-0fd930905f61.png)

**Comment by zakius** [comment]
duplicate of #192
