### ISSUE TITLE
v2.24.0 is not available via repos (AMO, Chrome Web Store)

### ISSUE THREAD

**Issue by QmwJlHuSg9pa** [SmartRSS/Smart-RSS#214]
Unable to install latest version (v2.24.0) on Firefox Release, as it [does not honour](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users) `"xpinstall.signatures.required": False`.

**Comment by zakius** [comment]
I'm sorry for trouble, somehow I forgot to upload this one and now it seems AMO validator became more strict and won't accept the package, I'll figure out what changed and upload the package as soon as possible

**Comment by Bec-de-Xorbin** [comment]
Is it possible to upload the latest (and unfortunately the last?) version to Chrome Web Store?

**Comment by zakius** [comment]
I just pushed the unchanged 2.24.0 to CWS, it's pending review now. Currently working on making it through updated AMO review and few extra changes , hopefully that won't take too long
