### ISSUE TITLE
update frequency setting is ignored

### ISSUE THREAD

**Issue by atomGit** [SmartRSS/Smart-RSS#223]
the ability to save changes to the update frequency from the feed folder context menu now works, however when refreshing all feeds from the context menu of "All feeds", the setting is ignored (all feeds are updated)

firefox 110
smart rss 2.25.0

**Comment by zakius** [comment]
The update all button was always meant to override that check so that's by design

**Comment by atomGit** [comment]
ah, ok! makes sense
