### ISSUE TITLE
Extension useless after last update

### ISSUE THREAD

**Issue by alvarozmg** [SmartRSS/Smart-RSS#236]
Hi. I was using Smart RSS everyday until the last update (2 weeks ago, I think?), and then I noticed that the thing was not fetching any new articles from my subscribed feeds. I removed the feeds and added them again, and then it would not fetch anything. I uninstalled the extension, reinstalled it, added the feeds... nothing. I tried installing it again just now in case it would have been fixed, but I encounter the same problem: no articles are pulled from the feeds.

I'm using Firefox 78.15.0esr (64-bit), on a Mac Book Pro with OSX El Capitan.

Hopefully this can be fixed, as this was the best RSS extension I found. Thanks.

**Comment by zakius** [comment]
I'll take a look what can be done to keep the support of 78, but you probably should get the latest ESR already

**Comment by alvarozmg** [comment]
Thanks, I tried to update the browser but is says it's updated. I tried to download and install the lates version but apparently I can't; probably because my OSX version.

Is there a way to install the previous version of the extension? That one worked just fine for me.

Thanks,
Alvaro

**Comment by zakius** [comment]
you should be able to just download it from AMO and install but I suggest exporting your feeds data and for extra safety backing up also your browser profile before you do that

**Comment by alvarozmg** [comment]
Unfortunately didn't work, but thanks anyway.
