### ISSUE TITLE
failing to fetch Odysee feed

### ISSUE THREAD

**Issue by atomGit** [SmartRSS/Smart-RSS#242]
it seems there might be a problem with fetching odysee feeds

feed: https://odysee.com/$/rss/@drsambailey:c

update or refresh doesn't pull any content for that feed

linux
firefox 115
smart rss 2.25.2

**Comment by zakius** [comment]
it worked for me just fine, could you try inspecting the extension in `about:debugging#/runtime/this-firefox` and checking if there's anything useful in the console when it fails?

**Comment by atomGit** [comment]
hmmm - it worked for me too when i deleted and re-added the feed - also a subsequent 'refetch' worked

i did check the URL though and the old one which i provided above was valid, so i dunno why re-adding it worked

i have other odysee feeds and they're working

i'll troubleshoot and re-open if the problem arises again
