### ISSUE TITLE
Remove items from trash after...

### ISSUE THREAD

**Issue by zakius** [SmartRSS/Smart-RSS#55]

**Comment by atomGit** [comment]
option to delete 'read' at add-on exit/tab close?

also option to bypass delete prompt as well as option to bypass 'trash' completely

**Comment by atomGit** [comment]
just wanted to add to this

i guess this depends somewhat on how read and unread articles are handled, but i personally see no need to have a trash bin - i think the way NewsFox did it worked well - it had an option to purge everything that was not in the feed so it handled trash automatically - when that was combined with the option to sort by read/unread, there was nothing left for the user to do - it was all handled automatically and all unread/new articles could be sorted to appear first

if someone want's to keep something, they can pin it i would think

on a totally off-topic note ... i never really understood the "threads" thing - i know the number dictates how many simultaneous connects can be made, but what should it be set it if, for instance, you have fast DSL?

**Comment by zakius** [comment]
I have some things in my mind but I feel like I have to redesign settings page before I get to adding more and more options, sometimes I have to think how to handle edge cases. I'll definitely leave the trash for people who got used to it and add flag to make `del` work as `shift+del`. I'd be happy to make it work like in NewsFox where it kept items on the list, just marking them as removed and only *marked as removed more* on refresh (kind of UID has to be stored to prevent article showing up again but all contents are removed to save space)

according the number... I don't know, before I took this project over it wasn't parallelized at all. Currently all the parsing happens in a single thread so it depends probably on the strength of your cores but it should be able to handle **a lot** you really just have to find it out yourself, on my setup it seems to get a bit clunky over 10 connections and 30 makes the reader view unresponsive but doesn't feel like it slows down the browser itself (like NewsFox does)
