### ISSUE TITLE
[feature] add filtering capability

### ISSUE THREAD

**Issue by atomGit** [SmartRSS/Smart-RSS#6]
re: #3 (point 5 and filtering) - i see that there's a search field and i think that's a good thing to have, but what i'm referring to is a filter system that auto-filters articles - so in other words the user creates a filer in the options (filter option) "headline contains" (string) "breaking" and then that article is mirrored in a special 'folder' for filtered items - for instance in [Feedbro](https://addons.mozilla.org/en-US/firefox/addon/feedbroreader/), that folder is labeled "starred items"

the purpose is make sure one doesn't miss something they are particularly interested in, so the article is copied to the special folder and the user can immediately see, upon clicking that folder (or category or whatever you want to call it) that something important has landed there rather than having to sift through potentially hundreds of articles - so this is just sort of an automated version of the current 'search' function, but indeed it can be quite handy

**Comment by zakius** [comment]
Okay, I see. This is indeed nice to have feature, though it's not high priority

**Comment by zakius** [comment]
As I got back to this issue it seems it's not actually filtering as creating multiple filters and listing only items meeting certain filters criteria but throwing all interesting items into one, common bag? Do you think I can use `Pinned` status for that? It would be fairly easy to do, just may require moving `Pinned` to the top of the list for better access or making it configurable (references #106)

**Comment by atomGit** [comment]
i think that'd be fine - move pinned to the top and use it for filtered feed items

the filtering in Feedbro was/is rather granular as i recall and i don't think all that is needed - perhaps just a single, multi-line text input control where one can enter words/phrases separated by a delimiter (comma, semicolon)

then there's the question of whether you want to provide options to search the title, body, or title and body for the key word(s) - in my case i think searching only titles would be sufficient

and then a question of what results to return - so if i enter 'cat' in the filter control, do we return feed titles with 'cat', 'cats', 'caterpillar', etc., and do we perhaps have wildcard (*) so only the whole word 'cat' is returned unless the filter key word is 'cat*' or '*cat*' which returns 'cats' and 'scatter', etc.

as for case-sensitivity, i think ignore case

while a wildcard could be omitted for simplicity, and just return only exact matches, i think it would be pretty beneficial to have - i'm thinking of use cases like 'COVID-19' which may simply appear in a title as 'COVID' or 'Covid' - if no wildcard, then one would have to list all forms of the word in the filter box, or just 'covid*' with a wildcard

<details>
<summary>very off-topic, but for those interested...</summary>
[Coronavirus (COVID-19, SARS-CoV-2) news and resources, updated daily](https://12bytes.org/articles/health/covid-19-coronavirus-information-resources)
</details>

**Comment by zakius** [comment]
I think I'll just make it work like search does (so if title, author and if you want contents contains specified string it's in, no whole words constrains), at least for first version

**Comment by zakius** [comment]
Implemented as of 2.21.0

**Comment by atomGit** [comment]
hi zakius - thanks for implementing this and, again, thanks a ton for your work on the extension - it's come a long way since you forked it
