### ISSUE TITLE
feature: better feed detection

### ISSUE THREAD

**Issue by atomGit** [SmartRSS/Smart-RSS#69]
i'm using S-RSS instead of Feedbro as my default and so i'm just mentioning these things as i come across them - sorry to bombard you with issues :)

Feedbro does pretty good at feed detection and it'd be great if Smart RSS were enhanced in this department, especially given Moz's decision to cut out the RSS stuff - i have an article here that might help...

[How to access RSS feeds for websites that don’t advertise one](https://12bytes.org/articles/tech/how-to-access-rss-feeds)

...however you probably don't want to be running non-standard checks for feeds outside of the `<head>` which is fine, but i'm wondering if you'd allow users to run a manual check that is more comprehensive than the auto-checking (the manual check would parse the entire page to look for patterns like those in the article)

youtube feeds and many others are really simple - you could use a simple template and just grab the channel ID to complete the feed URL...

`https://www.youtube.com/channel/[channel ID]`
becomes...
`https://www.youtube.com/feeds/videos.xml?channel_id=[channel ID]`

so when you come across `/youtube.com/channel/`, you could auto-create the feed URL and pop the feed icon in the address bar - same for bitchute.com and others

**Comment by zakius** [comment]
I'll be doing some non-standard checks for sure (related to #42 as Medium is quite popular), YouTube is even more popular so while much less people will use this feature I'll add it too

**Comment by zakius** [comment]
After thinking it through I decided to keep the built in detector simple as Page Actions are a bit messy, make it optional and add create heloer extension with extended abilities. This will also be usefull since Chromium differs a bit and my packaging toolkit got overly complicated.

**Comment by zakius** [comment]
Finally got to it, earlier added WordPress detection in case of layout explicitly removing the proper `link` tag (I encountered it in the wild already), now YouTube feed detection is added in the repository

I accumulated some important improvements so I'm going to publish this version sometime next week, in the meantime I may be able to add support for some other websites but it's not guaranteed

**Comment by atomGit** [comment]
thanks - BitChute would be my next pick since it's getting pretty popular - adding channel feeds should, i think, be the same as for YouTube
