### ISSUE TITLE
Sources collection becomes unavailable after SMART import

### ISSUE THREAD

**Issue by zakius** [SmartRSS/Smart-RSS#72]
Currently it's worked around by reloading extension after finishing import as mentioned in #70 but it has to be resolved properly

**Comment by atomGit** [comment]
hope this might help you out...

FF 66.0.5
S-RSS 2.0.36

after the initial feed import with .65, then the upgrade to .66, all was ok at first - after reading the news i closed S-RSS and later reopened its tab to find everything gone except the feed folders - feed sources and all (i know you already know about this) - so i closed and reopened the tab and all the sources were back, but when i tried a refresh the process stopped after only 1 feed was refreshed - then i F5'd to reload the tab and it stopped on 2 feeds - F5 again and it made it to 5 of my 129 feeds - F5 again and it made it to 8 - also the new (unread) headlines never show until the next F5

before all this i deleted all articles after i was done reading (if that makes a difference)

also the refresh speed seems extremely slow - Concurrent downloads is at 5

**Comment by zakius** [comment]
I meant that whole extension has to be reloaded, including background page (disable and enable it or restart the browser) and I made it reload after finishing import to work around this exact issue, but there are few other instances of GC kicking in (fortunately on 66 it happens much less often than on 56) and collecting references to some collections, hopefully I'll resolve this while refactoring the background process, but this will be a pretty big leap. Unfortunately I can't find the exact reason of these references being collected in the first place

**Comment by zakius** [comment]
This should be resolved by using messages instead of accessing background collection directly, this is a big task
