### ISSUE TITLE
Simple question: Does Smart-RSS has performance issues?

### ISSUE THREAD

**Issue by Decopi** [SmartRSS/Smart-RSS#98]
Hi @zakius ,

Firstly, thank you for your Smart-RSS' add-on/extension.

Today I read Ghacks' article (https://www.ghacks.net/2020/03/10/smart-rss-reader-is-a-feed-reader-extension-for-firefox-and-chrome). And I wrote the following comment:

"I just don't understand why this add-on/extension "SmartRSSReader" consumes so much RAM/CPU when compared (for example) to Feedbro add-on/extension (https://addons.mozilla.org/en-US/firefox/addon/feedbroreader/).

In FF' Nightly with 100 feeds, SmartRSSReader when inactive consumes around 4MB VS Feedbro that consumes around 1MB.

And when active, here is the huge exaggerated jump, SmartRSSReader may consume around 30MB (never saw an add-on/extension consuming so much RAM) VS Feedbro that consumes around 2MB (with same number of loaded feeds).

Please, don't get me wrong, SmartRSSReader has a nice and promising interface (reminds me NewFox), but from browser performance point of view, IMHO this add-on/extension has issues, or at least it needs a huge improvement here."

@zakius , I apologize in advance if I sounded too critic. I really liked Smart-RSS' interface and options. And I'm willing to move from Feedbro to Smart-RSS. But for that, I need Smart-RSS consuming a similar amount of CPU/RAM than Feedbro.

If you can improve that, it'll be fantastic!

Thank you in advance.

**Comment by zakius** [comment]
Internal data structure most likely requires a serious overhaul to improve performance and memory usage (it loads complete database to memory on startup), unfortunately this task seems too big to handle for a hobby project, at least for me.

So to put it short: I'm always aiming to improve, but in most cases I have to settle with low hanging fruits. But I'll see if I can skip loading article contents on startup and fetch them only to display

**Comment by Lichtenshtein** [comment]
Amaizing work, zakius!
