### ISSUE TITLE
Another viewtype...

### ISSUE THREAD

**Issue by XeonG** [SmartRSS/Smart-RSS#99]
Would be great to get another view type like https://addons.mozilla.org/en-US/firefox/addon/sage-like/  

where the site feed list is at top, and all the feeds for that site/xml feed are listed below.. clicking on one of those then just opens the site.

Maybe with a preview of the site feeds in a hover panel, but not a dedicated view.

**Comment by zakius** [comment]
I don't think I'd be able to pull it off in a reasonable timeframe, will leave this open to see if it gets more traction, maybe someone willing to help
